---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
    argocd.argoproj.io/sync-wave: "0"
  creationTimestamp: null
  name: assisted-deployment-pull-secret
  namespace: <replace me>
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    .dockerconfigjson: <replace me>
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: assisted-deployment-pull-secret
      namespace: <replace me>
    type: kubernetes.io/dockerconfigjson
